// Project info

name := "play-mongojack"

organization := "org.mongojack"

// The version comes from version.sbt, and is generated by the release plugin

scalaVersion := "2.10.0"

// Dependencies

libraryDependencies ++= Seq(
    "org.mongojack" % "mongojack" % "2.0.0-RC5",
    "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.2.0",
    "play" %% "play" % "2.1.1" % "provided"
)

// Test dependencies

libraryDependencies ++= Seq(
    "org.specs2" %% "specs2" % "1.13" % "test",
    "play" %% "play-test" % "2.1.1" % "test"
)
